### ISSUE TITLE
bonding between two nodes are not happening

### ISSUE THREAD

**Issue by primohan01** [ros/bond_core#20]
Hi,
i got one issue line No .  13 " bond.waitUntilBroken(); " in this example for bond, its giving error ambiguity .   and not forming Bond also. give me solution  as soon as possible.

Toggle line numbers

   1 #include <bondcpp/bond.h>
   2 
   3 std::string id = generateUniqueId();
   4 // Sends id to B using a service or action
   5 bond::Bond bond("example_bond_topic", id);
   6 bond.start();
   7 if (!bond.waitUntilFormed(ros::Duration(1.0)))
   8 {
   9     ROS_ERROR("ERROR!");
  10     return false;
  11 }
  12 // ... do things with B ...
  **# _13 bond.waitUntilBroken();_**
  14 printf("B has broken the bond\n");

Process B:
Toggle line numbers

   1 #include <bondcpp/bond.h>
   2 
   3 // Receives id from A using a service or action
   4 bond::Bond bond("example_bond_topic", id);
   5 bond.start();
   6 // ... do things ...
   7 bond.breakBond();

**Comment by mikaelarguedas** [comment]
this is example code to show the concept. It is not expected to be compiled as is. The example is indeed outdated and not matching the current API, thanks for pointing it out.

Below an example of compilable bond example:
ProcessA.cpp:
```c++
#include <bondcpp/bond.h>
#include <ros/spinner.h>

int main(int argc, char **argv)
{
  ros::init(argc, argv, "ProcessA", true);
  ros::AsyncSpinner spinner(1);
  spinner.start();
  bond::Bond bond("example_bond_topic", "myBondId123456");
  printf("A starting bond\n");
  bond.start();
  printf("A waiting for bond to be formed\n");
  if (!bond.waitUntilFormed(ros::Duration(10.0)))
  {
      ROS_ERROR("ERROR!");
      return false;
  }
  printf("A waiting for bond to be broken\n");
  // ... do things with B ...
  bond.waitUntilBroken(ros::Duration(20.0));
  printf("B has broken the bond\n");
}
```

ProcessB.cpp
```c++
#include <bondcpp/bond.h>
#include <ros/spinner.h>

int main(int argc, char **argv)
{
  ros::init(argc, argv, "ProcessB", true);
  ros::AsyncSpinner spinner(1);
  spinner.start();

  bond::Bond bond("example_bond_topic", "myBondId123456");
  bond.start();
  // ... do things ...

  fprintf(stdout, "Bond started\n");
  for (size_t i = 0; i < 2000000000; i++) {} 
  fprintf(stdout, "Breaking bond\n");
  bond.breakBond();
  fprintf(stdout, "Bond stopped\n");
}
```

Hope this helps

**Comment by mikaelarguedas** [comment]
I'm going to close this for now because I think the question has been answered. @primohan01  feel free to ask your questions on [ROS Answers](http://answers.ros.org/questions/)
