### ISSUE TITLE
bondpy SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/bond_core#23]
when building from source

```
running build
running build_py
creating /home/ale/catkin_ws/build_isolated/bondpy/lib
creating /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy
copying python/bondpy/BondSM_sm.py -> /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy
copying python/bondpy/__init__.py -> /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy
copying python/bondpy/bondpy.py -> /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy
running install
running install_lib
creating /opt/ros/lunar/lib64/python3.5/site-packages/bondpy
copying /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy/BondSM_sm.py -> /opt/ros/lunar/lib64/python3.5/site-packages/bondpy
copying /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy/__init__.py -> /opt/ros/lunar/lib64/python3.5/site-packages/bondpy
copying /home/ale/catkin_ws/build_isolated/bondpy/lib/bondpy/bondpy.py -> /opt/ros/lunar/lib64/python3.5/site-packages/bondpy
byte-compiling /opt/ros/lunar/lib64/python3.5/site-packages/bondpy/BondSM_sm.py to BondSM_sm.cpython-35.pyc
byte-compiling /opt/ros/lunar/lib64/python3.5/site-packages/bondpy/__init__.py to __init__.cpython-35.pyc
byte-compiling /opt/ros/lunar/lib64/python3.5/site-packages/bondpy/bondpy.py to bondpy.cpython-35.pyc
running install_egg_info
Writing /opt/ros/lunar/lib64/python3.5/site-packages/bondpy-1.7.19-py3.5.egg-info
  File "/opt/ros/lunar/lib64/python3.5/site-packages/bondpy/BondSM_sm.py", line 38
    raise statemap.TransitionUndefinedException, msg
                                               ^
SyntaxError: invalid syntax

-- Installing: /opt/ros/lunar/lib/pkgconfig/bondpy.pc
-- Installing: /opt/ros/lunar/share/bondpy/cmake/bondpyConfig.cmake
-- Installing: /opt/ros/lunar/share/bondpy/cmake/bondpyConfig-version.cmake
-- Installing: /opt/ros/lunar/share/bondpy/package.xml
<== Finished processing package [153 of 241]: 'bondpy'
```

**Comment by mikaelarguedas** [comment]
Yeah bond is not python3 compatible yet. can you give a shot to https://github.com/ros/bond_core/pull/24 and post here any further failure ? (I just replaced what was obviously not python3 compatible but I'm pretty sure there is more)

**Comment by Alessandro-Barbieri** [comment]
I changed my default python to python2.7 and now works. I can't find more informations on what python ROS is supposed to use.

**Comment by mikaelarguedas** [comment]
The place to find the targeted dependencies of each ROS distribution is REP3: http://www.ros.org/reps/rep-0003.html.
I'd appreciate if you give it a try using python 3 and give feedback here though.

**Comment by Alessandro-Barbieri** [comment]
@mikaelarguedas Thanks, testing with python3 is hard because these are all silent failures that will not break the build, so I can detect them only if I stare at the build log and my eyes are fast enough to read.
For now with python2.7 still I haven't a working installation, I think I'll test after i got all installed right.

P.S. I'm on Gentoo, following http://wiki.ros.org/lunar/Installation/Source (I had to add some cmake switches and environment variables) if it matters

**Comment by mikaelarguedas** [comment]
@Alessandro-Barbieri appreciate it, yeah getting everything to build properly with python2 is definitely the first step before looking at the python3 compatibility

> tfoote big goal: add a python3 syntax checker to all the modules

I think that will be hard to enforce. None of the ROS distributions require python3 (it a "nice to have") so I don't think we can enforce this

**Comment by mikaelarguedas** [comment]
@Alessandro-Barbieri I'm going to close this for now, feel free to comment here when you have a chance to try it out and we will reopen / address the remaining python3 incompatibilities
