### ISSUE TITLE
bondcpp: UUID_INCLUDE_DIRS missing

### ISSUE THREAD

**Issue by peci1** [ros/bond_core#35]
In `CMakeLists.txt` of bondcpp, there's no mention of `UUID_INCLUDE_DIRS`. I've just found out it's a problem on a system without root privileges where I'm compiling ROS from sources and installing some dependencies in non-standard paths. If the libuuid-dev files aren't installed in a default system location, the build process fails to find `uuid/uuid.h`, even though the CMake module finds the correct include dir.

Looking in nodelet, `UUID_INCLUDE_DIRS` are exported there in `catkin_package(INCLUDE ...)` and not used as an `include_directory()`. I'm not sure that works, too, because uuid is used there only inside a cpp file and in no header file. The same situation is in bondcpp - I've only found the include inside .cpp files.

So my assumption is adding 

    include_directories(${UUID_INCLUDE_DIRS})

and not adding `UUID_INCLUDE_DIRS` to `catkin_package(INCLUDE ...)` should solve the issue. I tested it on my system and it works. 

If all my assumptions are correct, uuid should only be marked as `<build_depend>` and `<exec_depend>` in package.xml.

I'll send a PR with this change so that CI can be run on it, but it'd also be nice if somebody tested it on his system. For the test, I think the following is needed:

 - move all files from `dpkg -L libuuid-dev` to a different directory
 - re-run CMake and make sure it fails to find uuid
 - re-run CMake with `CMAKE_PREFIX_PATH` set so that cmake finds the moved include dir
 - build the package

**Comment by mikaelarguedas** [comment]
@peci1 thanks for reporting this. You are totally right this dependency should not be exported and both nodelet and bondcpp should find the package themselves, include `UUID_INCLUDE_DIRS` where needed and link against `UUID_LIBRARIES` when needed.

I opened https://github.com/ros/nodelet_core/pull/74 and https://github.com/ros/bond_core/pull/36 to address this.
I haven't tested the relocation of the files you suggested. Can you try these PRs when you get a chance and comment here with the outcome?

Thanks!

**Comment by mikaelarguedas** [comment]
@peci1 I'm going to go ahead and merge the referenced PRs so that they're part of the next release, please feel free to comment here reporting if it solves your problem or not

**Comment by peci1** [comment]
Yes, I've successfully tested at least with nodelet_core and it works. Thanks.

**Comment by mikaelarguedas** [comment]
thanks @peci1 for reporting the issue and the feedback :+1:
