### ISSUE TITLE
Creation of new banch as ros2-devel

### ISSUE THREAD

**Issue by kishornaik10** [ros/bond_core#42]
Hi,
We have ported Bond package in ros2, and want to share this development.
https://discourse.ros.org/t/migration-of-bond-core-package/6399
Thanks,
Kishor

**Comment by mjcarroll** [comment]
Great! Thank you for your willingness to contribute.  I have created the `ros2` branch for you to create pull requests against for right now: https://github.com/ros/bond_core/tree/ros2

If we find that the refactoring is larger than anticipated, then we may consider creating a `ros2/bond_core` repository.

Can you give a few details about how you intend to port the behavior and functionality of `bond`?

**Comment by kishornaik10** [comment]
Hello @mjcarroll , Please find pull request https://github.com/ros/bond_core/pull/43 for bond-core in ros2.

**Comment by kishornaik10** [comment]
> Great! Thank you for your willingness to contribute. I have created the `ros2` branch for you to create pull requests against for right now: https://github.com/ros/bond_core/tree/ros2
> 
> If we find that the refactoring is larger than anticipated, then we may consider creating a `ros2/bond_core` repository.
> 
> Can you give a few details about how you intend to port the behavior and functionality of `bond`?

We have carried out basic porting of functionality for bond-core which is present in ROS.
As we are porting diagnostic package from ROS to ROS2, and bond-core is one of its dependency.
So we have ported Bond-core to achieve this.

It is a bond between 2 nodes (say Node 1 & Node 2). The Bond is established through Service/Action exchanging bond id so that they understand each other and ties with an id. 
on_broken, on_formed functions can be assigned to it, status can be seen/monitored. 
And later it can be checked for time-outs i.e. connect, disconnect, heartbeat timeout 
The functionality is achieved thorough work around  for timers. 

Please review and suggest modifications if any. 

Thanks, 
Kishor

**Comment by kishornaik10** [comment]
Hello @mjcarroll ,
I have added ros2_migration_readme.md which contains overview and changes related to migration. 
Please find pull request  https://github.com/ros/bond_core/pull/43 for bond-core in ros2.
Waiting for your valuable feedback.

Thanks,
Kishor

**Comment by mjcarroll** [comment]
Perfect, thank you.  I'm currently out of the office, but will review this as soon as I get back.
