### ISSUE TITLE
Static linking to uuid which might be GPL?

### ISSUE THREAD

**Issue by 130s** [ros/bond_core#47]
IANAL and I'm not entirely sure if the following concern is valid.

`bondcpp` [statically links to uuid](https://github.com/ros/bond_core/blob/4836d34d6f325ec79e76ab48e1977083854b9bca/bondcpp/CMakeLists.txt#L27), and `bond.cpp` [includes a header uuid.h](https://github.com/ros/bond_core/blob/4836d34d6f325ec79e76ab48e1977083854b9bca/bondcpp/src/bond.cpp#L39). 

On Ubuntu [rosdep key uuid](https://github.com/ros/rosdistro/blob/2540e78253740ba105fcf8d205d20be5f9855f9d/rosdep/base.yaml#L5101) references to [uuid-dev](https://packages.ubuntu.com/xenial/uuid-dev). Content of `/usr/share/doc/uuid-dev/copyright` shows large part of the package is licensed GPL-2+. I haven't found uuid-dev's repo nor website, but [package info on debian.org](https://metadata.ftp-master.debian.org/changelogs/main/u/util-linux/util-linux_2.33.1-0.1_copyright) also lists the similar copyright file with GPL-2+.

Ins't bondcpp considered to be a derived work, and doesn't GPL force the derived work to be declared as GPL?

**Comment by tfoote** [comment]
Viewing the contained copyright file in the debian package: http://changelogs.ubuntu.com/changelogs/pool/main/u/util-linux/util-linux_2.27.1-6ubuntu3/copyright

There are several licenses for different parts of that package. 

libuuid from that package is BSD licensed:
```
Files: libuuid/*
       libuuid/src/*
       libuuid/man/*
Copyright: 1996, 1997, 1998, 1999, 2007 Theodore Ts'o.
           1999 Andreas Dilger (adilger@enel.ucalgary.ca)
License: BSD-3-clause
```

This includes the header file you mention is used and the source for the library linked against.

**Comment by 130s** [comment]
Closing same as https://github.com/ros/nodelet_core/issues/87#issuecomment-471710887
