### ISSUE TITLE
queue_size for publisher

### ISSUE THREAD

**Issue by jihoonl** [ros/bond_core#5]
queue_size is recommended for Publishers from indigo. I wish bondpy would give me any syntax warning. I couldn't create a PR since it is only branch which would influence groovy, hydro, and indigo all of them..

Related discussions : http://ros-users.122217.n3.nabble.com/RFC-warning-for-lacking-queue-size-for-python-publishers-in-Indigo-tt4020772.html

Related PR : https://github.com/ros/ros_comm/pull/372

**Comment by mikepurvis** [comment]
Resolved in 4d18c52e69aaca9415df2818b584437312dd4b78.

**Comment by mikaelarguedas** [comment]
Released in https://github.com/ros/bond_core/issues/13#issuecomment-227805043
