### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by ahcorde** [ros/bond_core#60]
@mjcarroll can you create a `noetic-devel` branch ? 

We need to do some changes according with the migration guide http://wiki.ros.org/noetic/Migration

I created this PR but it was targeting kinetic  https://github.com/ros/bond_core/pull/59

**Comment by mjcarroll** [comment]
Done: https://github.com/ros/bond_core/tree/noetic-devel.

Are these changes something that could also land in `melodic`?  If so, then I could make `melodic-devel`, and we can cut releases for both distros off of that.

**Comment by mjcarroll** [comment]
Based on this, it looks like it could land on `kinetic-devel`?

https://github.com/ros/genlisp/pull/17

**Comment by ahcorde** [comment]
thank you @mjcarroll https://github.com/ros/bond_core/pull/61

**Comment by mjcarroll** [comment]
Closed by #61, thanks!
