### ISSUE TITLE
Release Bond for ROS2 Dashing / Foxy

### ISSUE THREAD

**Issue by SteveMacenski** [ros/bond_core#63]
Hi,

It would be great to have this released for ROS2 to use.

**Comment by sloretz** [comment]
+1 to release to ROS Rolling Ridley as well

```
nav2_util: Cannot locate rosdep definition for [bond]
nav2_lifecycle_manager: Cannot locate rosdep definition for [bondcpp]
```

**Comment by SteveMacenski** [comment]
See #67, we need to actually fix bond before its worth releasing. That PR resolves the vast majority of problems (and all that I first-hand experienced). By the time Galactic rolls by, if we haven't had that merged, Navigation2 will be un-releasable.

**Comment by SteveMacenski** [comment]
@mjcarroll could we get a release? :pray:

**Comment by clalancette** [comment]
> @mjcarroll could we get a release? pray

Just FYI, @mjcarroll is on vacation this week, so you probably won't get a response until next week.

**Comment by SteveMacenski** [comment]
Thanks for the note, no particular rush

**Comment by SteveMacenski** [comment]
@mjcarroll can we get foxy / dashing branches? There's an API change to Duration that I'm fixing right now for ROS2 master but not sure it should be reflected on the single `ros2` branch used by all distros. 

Just in general though, it would be great if this had bloom run on it for at minimum Foxy and Galactic in a couple weeks, this will block Nav2 from releasing.

**Comment by mjcarroll** [comment]
Okay, since `foxy` and `dashing` seem to be sharing sources at the moment, I released both off of a branch called `dashing-devel`.

* Dashing: https://github.com/ros/rosdistro/pull/27257
* Foxy: https://github.com/ros/rosdistro/pull/27258

For rolling, I released off the `ros2` branch (which is still the same as `dashing-devel`, but gives more latitude).

* Rolling: https://github.com/ros/rosdistro/pull/27259

**Comment by gomandr** [comment]
Hi,

It seems `bondcpp` has been released for `foxy` ([ros index](https://index.ros.org/p/bondcpp/github-ros-bond_core/#foxy-overview)), yet when I try to install it in a (simplified) docker:

```
FROM ros:foxy
RUN apt-get update \
    && apt-get install -y ros-foxy-bondcpp
```

I get the following error: `E: Unable to locate package ros-foxy-bondcpp`

Am I missing something here ? I'm actually trying to build [grid_map](https://github.com/ANYbotics/grid_map) in a docker and failing to get this package when installing dependencies.  

Thanks for your help.

**Comment by clalancette** [comment]
It's been failing to build for a while: https://build.ros2.org/job/Fbin_uF64__bondcpp__ubuntu_focal_amd64__binary/

Looking at the latest output, it looks like it is missing a dependency on `pkg-config` in the package.xml, so it fails to build.  Here's a PR that fixes it: https://github.com/ros/bond_core/pull/77 .

@mjcarroll Can you review, merge, and re-release into Foxy?

**Comment by clalancette** [comment]
OK, it looks like bondcpp is building in Foxy again thanks to the work of @mjcarroll : https://build.ros2.org/job/Fbin_uF64__bondcpp__ubuntu_focal_amd64__binary/

You can also now install it if you are using the testing repository, with `sudo apt-get install ros-foxy-bondcpp`.  This will make it into the next Foxy sync.

As far as Dashing is concerned, it would need a lot more work, and Dashing EOL is in a very short while.  So I think we won't bother with Dashing here.

Given all of that, I'm going to close this out.
