### ISSUE TITLE
Buiding the pakcage "ros2" branch fails with "‘from_nanoseconds’ is not a member of ‘rclcpp::Duration’"

### ISSUE THREAD

**Issue by ByLiZhao** [ros/bond_core#71]
While building the package, "ros2" branch with ros2-foxy, the compiler complains that:

> ‘from_nanoseconds’ is not a member of ‘rclcpp::Duration’

**Comment by clalancette** [comment]
Yes, the "ros2" branch only builds against Rolling.  To build it for Foxy, you'll need to use the "dashing-devel" branch.
