### ISSUE TITLE
Colcon Build Branch ROS 2 Not working

### ISSUE THREAD

**Issue by nuriafegva** [ros/bond_core#75]
ROS 2 Colcon Build not working.

It is getting stuck with broncpp givint out this error at the beginning: error: ‘from_nanoseconds’ is not a member of ‘rclcpp::Duration’ 

Please help :)

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Please note that there is no where near enough information in this post to be able to help you. This sounds like an error where you're using incompatible branches. When you ask your question make sure to explain how you've setup your full environment so people can help you debug it.
