### ISSUE TITLE
Which variantof the BSD license does this project use?

### ISSUE THREAD

**Issue by jiaxshi** [ros/bond_core#98]
We get "BSD" in package.xml. There are multiple variants of the BSD license. Which specific one applies to our project?  BSD-3-Clause?

**Comment by clalancette** [comment]
It is [3-Clause BSD](https://opensource.org/license/bsd-3-clause); you can see it [here](https://github.com/ros/bond_core/blob/b65dc1681a1b2930f7691c7a39d2aec9c1a67b6a/bondcpp/include/bondcpp/BondSM_sm.hpp#L1-L28).
